kind: HTTPScaledObject
apiVersion: http.keda.sh/v1alpha1
metadata:
    name: openwebui
    namespace: scale-to-zero
spec:
    hosts:
    - open-webui.localtest.me
    pathPrefixes:
    - /
    scaleTargetRef:
        name: open-webui-deployment
        kind: Deployment
        apiVersion: apps/v1
        service: open-webui-service
        port: 8080
    replicas:
        min: 0
        max: 1
    scaledownPeriod: 600
    scalingMetric:
        requestRate:
            targetValue: 20
