---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
- apiGroups:
  - ""
  resources:
  - namespaces
  - persistentvolumeclaims
  - pods
  - resourcequotas
  - serviceaccounts
  - services
  verbs:
  - '*'
- apiGroups:
  - apps
  resources:
  - deployments
  - statefulsets
  verbs:
  - '*'
- apiGroups:
  - apps.aichatworkspaces.io
  resources:
  - aichatworkspaces
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps.aichatworkspaces.io
  resources:
  - aichatworkspaces/finalizers
  verbs:
  - update
- apiGroups:
  - apps.aichatworkspaces.io
  resources:
  - aichatworkspaces/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - http.keda.sh
  resources:
  - httpscaledobjects
  verbs:
  - '*'
- apiGroups:
  - metrics.k8s.io
  resources:
  - pods
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - networking.k8s.io
  resources:
  - ingresses
  verbs:
  - '*'
