---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - apps.aichatworkspaces.io
  resources:
  - aichatworkspaces
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps.aichatworkspaces.io
  resources:
  - aichatworkspaces/finalizers
  verbs:
  - update
- apiGroups:
  - apps.aichatworkspaces.io
  resources:
  - aichatworkspaces/status
  verbs:
  - get
  - patch
  - update
