apiVersion: v1
kind: ConfigMap
metadata:
  name: envoy-config
  labels:
    app: envoy
data:
  envoy.yaml: |
    static_resources:
      listeners:
        - name: listener_0
          address:
            socket_address:
              address: 0.0.0.0
              port_value: 8080
          filter_chains:
            - filters:
                - name: envoy.filters.network.http_connection_manager
                  typed_config:
                    "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
                    stat_prefix: ingress_http
                    codec_type: AUTO
                    stream_idle_timeout: 300s
                    common_http_protocol_options:
                      idle_timeout: 120s          
                    route_config:
                      name: lingress_http
                      virtual_hosts:
                        - name: ingress_http
                          domains: ["*"]
                          routes:
                            - match:
                                prefix: "/"
                                headers:
                                - name: "Authorization"
                                  exact_match: "Basic b2xsYW1hOm9sbGFtYQ=="
                              route:
                                timeout: 0s
                                #idle_timeout: 120s
                                cluster: app_service
                                retry_policy:
                                  num_retries: 3
                                  per_try_timeout: 1s
                    http_filters:
                      - name: envoy.filters.http.router
      clusters:
        - name: app_service
          connect_timeout: 0.25s
          type: STATIC
          lb_policy: round_robin
          load_assignment:
            cluster_name: app_service
            endpoints:
              - lb_endpoints:
                  - endpoint:
                      address:
                        socket_address:
                          address: 127.0.0.1
                          port_value: 11434  # Points to the main app container
    admin:
      access_log_path: "/tmp/admin_access.log"
      address:
        socket_address:
          address: 0.0.0.0
          port_value: 9901
