apiVersion: v1
kind: Service
metadata:
  name: ollama-service-two
  labels:
    app.kubernetes.io/name: ollama-service
spec:
  selector:
    app: envoy
  ports:
    - protocol: TCP
      port: 11434
      targetPort: 11434
