apiVersion: v1
kind: Service
metadata:
  name: aichatworkspace-api
  labels:
    app.kubernetes.io/name: aichatworkspace-api
    app.kubernetes.io/instance: ollama-api
    app.kubernetes.io/version: 0.4.1
    app.kubernetes.io/component: service-endpoint
    app.kubernetes.io/part-of: ollama-api
    app.kubernetes.io/managed-by: aichat-workspace-operator
spec:
  selector:
    control-plane: controller-manager
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
