kind: HTTPScaledObject
apiVersion: http.keda.sh/v1alpha1
metadata:
    namespace: team-a-aichat
    name: team-a-aichat-openwebui
spec:
    hosts:
    - team-a-aichat.openwebui.localtest.me
    pathPrefixes:
    - /
    scaleTargetRef:
        name: team-a-aichat-openwebui
        kind: Deployment
        apiVersion: apps/v1
        service: team-a-aichat-openwebui
        port: 8080
    replicas:
        min: 0
        max: 1
    scaledownPeriod: 3600
    scalingMetric:
        requestRate:
            targetValue: 20
