apiVersion: apps.aichatworkspaces.io/v1alpha1
kind: AIChatWorkspace
metadata:
  labels:
    app.kubernetes.io/name: aichat-workspace-operator
    app.kubernetes.io/managed-by: kustomize
  name: aichatworkspace-team-a
  namespace: aichat-workspace-operator-system
spec:
  workspaceName: team-a-aichat
  workspaceENV: dev
  models:
    - gemma2:2b
    - llama3.2:1b
    - qwen2.5-coder:1.5b
    - smollm2:latest
    - codegemma:2b
