apiVersion: apps.aichatworkspaces.io/v1alpha1
kind: AIChatWorkspace
metadata:
  labels:
    app.kubernetes.io/name: aichat-workspace-operator
    app.kubernetes.io/managed-by: kustomize
  name: aichatworkspace-team-a
  namespace: aichat-workspace-operator
spec:
  workspaceName: team-a-aichat
  models:
    - gemma2:2b
    - phi3
