apiVersion: apps.aichatworkspaces.io/v1alpha1
kind: AIChatWorkspace
metadata:
  labels:
    app.kubernetes.io/name: aichat-workspace-operator
    app.kubernetes.io/managed-by: kustomize
  name: aichatworkspace-sample
  namespace: aichat-workspace-operator-system
spec:
  workspaceName: aichat-sample
  workspaceENV: dev
  models:
    - gemma2:2b
    - phi3.5:latest
